#ifndef BITMARK_SDK_VERSION_H
#define BITMARK_SDK_VERSION_H

#define BITMARK_VERSION_MAJOR 0
#define BITMARK_VERSION_MINOR 1
#define BITMARK_VERSION_BUILD 0

#define BITMARK_STR_HELPER(x) #x
#define BITMARK_STR(x) BITMARK_STR_HELPER(x)

#define BITMARK_VERSION BITMARK_STR(BITMARK_VERSION_MAJOR)\
  "." BITMARK_STR(BITMARK_VERSION_MINOR)\
  "." BITMARK_STR(BITMARK_VERSION_BUILD)

#endif // BITMARK_SDK_VERSION_H
